oc_platform_home:
    path: /{page}
    defaults: 
        _controller: OCPlatformBundle:Advert:index
        page: 1
    requirements:
        page: \d*
    
oc_platform_view:
    path: /advert/{advert_id}
    defaults:
        _controller: OCPlatformBundle:Advert:view
    requirements:
        advert_id: \d+
        
oc_platform_view_slug:
    path: /{year}/{slug}.{_format}
    defaults: 
        _controller: OCPlatformBundle:Advert:viewSlug
        _format: html
    requirements:
        year: \d{4}
        _format: html|xml
    
oc_platform_add:
    path: /add
    defaults: 
        _controller: OCPlatformBundle:Advert:add
    
oc_platform_edit:
    path: /edit/{id}
    defaults:
        _controller: OCPlatformBundle:Advert:edit
    requirements:
        id: \d+

oc_platform_delete:
    path: /delete/{id}
    defaults:
        _controller: OCPlatformBundle:Advert:delete
    requirements:
        id: \d+
        
oc_platform_application:
    path: /application/{id}
    defaults:
        _controller: OCPlatformBundle:Advert:application
    requirements:
        id: \d+     

oc_platform_purge:
    path: /purge/{days}
    defaults:
        _controller: OCPlatformBundle:Advert:purge
    requirements:
        days: \d+
    
oc_platform_purge_service:
    path: /purgeservice
    defaults:
        _controller: OCPlatformBundle:Advert:purgeService

oc_platform_test_validator:
    path: /test_validator
    defaults:
        _controller: OCPlatformBundle:Advert:testValidator
        
oc_platform_test_param_converter:
    path: /test_param_converter/{advert_id}/applications/{application_id}
    defaults:
        _controller: OCPlatformBundle:Advert:testParamConverter 
    requirements:
        advert_id: \d+
        application_id: \d+       
        
oc_platform_test_date_param_converter:
    path: /test_date_param_converter/{date}
    defaults:
        _controller: OCPlatformBundle:Advert:testDateParamConverter      
    requirements:
        date: "[0-9]{4}-[0-9]{2}-[0-9]{2}"

oc_platform_paramconverter:
    path: /test_param_converter/{json}
    defaults:
        _controller: "OCPlatformBundle:Advert:ParamConverter"