services:
#    oc_platform.example:
#        class: OC\PlatformBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    oc_platform.antispam:
        class: OC\PlatformBundle\Services\OCAntispam
        arguments:
            - "@mailer"
            - 5
        calls:
            - [ setLocale, ["%locale%"] ]
    oc_platform.application_mailer:
        class: OC\PlatformBundle\Services\ApplicationMailer
        arguments:
            - "@mailer"
    oc_platform.application_creation.listener:
        class: OC\PlatformBundle\Services\ApplicationCreationListener
        arguments:
            - "@oc_platform.application_mailer"
        tags:
            - { name: doctrine.event_listener, event: postPersist }
    oc_platform.purger.advert:
        class: OC\PlatformBundle\Services\PurgerAdvert
        arguments:
            - "@doctrine.orm.entity_manager"
    oc_platform.validator.antiflood:
        class: OC\PlatformBundle\Validator\AntifloodValidator
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@request_stack"
        tags:
            - { name: validator.constraint_validator, alias: oc_platform_antiflood }
    oc_platform.twig.antispam_extension:
        class: OC\PlatformBundle\Twig\AntispamExtension
        arguments:
            - "@oc_platform.antispam"
        tags:
            - { name: twig.extension }
            
    oc_platform.form.ckeditor:
        class: OC\PlatformBundle\Form\CkeditorType
        tags:
            - { name: form.type, alias: ckeditor }   
                   
    oc_platform.beta.html_adder:
        class: OC\PlatformBundle\Beta\BetaHTMLAdder
        
    oc_platform.beta.listener:
        class: OC\PlatformBundle\Beta\BetaListener
        arguments:
            - "@oc_platform.beta.html_adder"
            - "2017-07-01"
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: processBeta, priority: 2 }
   
    oc_platform.bigbrother.message_notificator:
        class: OC\PlatformBundle\Bigbrother\MessageNotificator
        arguments:
            - "@mailer"
            
    oc_platform.bigbrother.listener:
        class: OC\PlatformBundle\Bigbrother\MessageListener
        arguments:
            - "@oc_platform.bigbrother.message_notificator"
            - ["alexandre", "marine", "pierre", "Michael"]       
        tags:
            - { name: kernel.event_listener, event: oc_platform.post_message, method: processMessage }           
                          
    oc_platform.eventListener.souscripteur:
        class: OC\PlatformBundle\EventListener\SouscripteurListener
        arguments:
            - "@oc_platform.bigbrother.message_notificator"
            - ["alexandre", "marine", "pierre", "Michael"]   
            - "@oc_platform.beta.html_adder"
            - '2017-11-01'
        tags:
            - { name: kernel.event_subscriber }      
    
    oc_platform.paramconverter.json:
        class: OC\PlatformBundle\ParamConverter\JsonParamConverter
        tags:
            - { name: request.param_converter }